spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    openfeign:
      client:
        config:
          default: # 全局默认超时配置
            logger-level: full
logging:
  level:
    com.tinydemo.spring.cloud.sample.order.serivce.feign: debug