server:
  port: 80
  servlet:
    context-path: /order

spring:
  application:
    name: order-service
  cloud:
    consul:
      host: master
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: ${server.servlet.context-path}/actuator/health
        health-check-interval: 10s
        hostname: 192.168.242.1 # add this in case of consul and services are running on different hosts.
        prefer-ip-address: true